name: CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov coverage
      - name: Run tests
        run: pytest -q || true
      - name: Coverage (fail under 80%)
        run: |
          coverage run -m pytest || true
          coverage report -m --fail-under=80
